# Generated by Django 4.1.5 on 2023-02-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50)),
                ('acctName', models.CharField(max_length=100)),
                ('acctNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('programmingLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_programming_language', to='accts.programminglanguage')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='programmingLanguageYearsOfExperience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBudget', models.IntegerField(default=0)),
                ('withdrawalPurpose', models.CharField(max_length=200)),
                ('withdrawal', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_bank', to='accts.mybank')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_withdrawal', to='accts.person')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingTaskDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskIsDone', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accts.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_task_done', to='accts.programmingtask')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_point', to='accts.person')),
                ('taskDone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_task_done_point', to='accts.programmingtaskdone')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBudget', models.IntegerField(default=0)),
                ('allocatedBudget', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_budget', to='accts.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='bankDetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_bankdetails', to='accts.mybank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='programmingLanguage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_programming_language', to='accts.programminglanguage'),
            preserve_default=False,
        ),
    ]
