# Generated by Django 4.1.5 on 2023-02-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accts', '0002_mybank_programminglanguage_programmingtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybank',
            name='acctNo',
            field=models.CharField(max_length=15),
        ),
    ]
