# Generated by Django 4.1.5 on 2023-02-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accts', '0004_rename_mybank_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLiteracyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='point',
            old_name='taskDone',
            new_name='programingTaskDone',
        ),
        migrations.AddField(
            model_name='point',
            name='digitalLiteracyTaskDone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='digital_literacy_task_done_point', to='accts.programmingtaskdone'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('programmingLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee_programming_language', to='accts.programminglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalLiteracyTaskDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskIsDone', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accts.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_literacy_task_done', to='accts.digitalliteracytask')),
            ],
        ),
        migrations.AddField(
            model_name='digitalliteracytask',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_literacy_invitee', to='accts.invitee'),
        ),
    ]
