# Generated by Django 4.1.5 on 2023-02-18 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accts', '0005_digitalliteracytask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalliteracytask',
            name='invitee',
        ),
        migrations.AddField(
            model_name='digitalliteracytaskdone',
            name='invite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='digital_literacy_invitee', to='accts.invitee'),
            preserve_default=False,
        ),
    ]
